Repository eshwinrio/kaya-hr, pull requests merged in 2024-03, with the labels that each got.

#28 feature/KAYA-27-Write-a-script-to-seed-default-entries
  auth-server/.env.template
  auth-server/README.md
  auth-server/package.json
  auth-server/prisma/migrations/20240217185257_init/migration.sql
  auth-server/prisma/migrations/20240218184319_application_role_connector/migration.sql
  auth-server/prisma/migrations/20240229222338_kaya_27/migration.sql
  auth-server/prisma/schema.prisma
  auth-server/prisma/seed.js
  auth-server/src/config/environment.ts
  auth-server/src/lib/token.ts
  auth-server/src/middlewares/check-application-roles.ts
  auth-server/src/middlewares/require-access-token.ts
  auth-server/src/routers/auth-router.ts
  auth-server/src/routers/user-router.ts
  auth-server/tsconfig.json
  hr-resource/.env.template
  hr-resource/README.md
  hr-resource/package.json
  hr-resource/prisma/schema.prisma
  hr-resource/prisma/seed.js
  hr-resource/src/config/environment.ts
  hr-resource/tsconfig.json
Labels: enhancement

#29 feature/KAYA-28-Compose-a-middleware-for-user-application-checking
  auth-server/src/middlewares/require-user.ts
  auth-server/src/middlewares/require-userApplication-link.ts
  auth-server/src/routers/auth-router.ts
  auth-server/src/routers/user-router.ts
  hr-resource/.env.template
  hr-resource/src/lib/apollo.ts
Labels: enhancement

#30 feature/KAYA-52-Build-sync-users-endpoint
  auth-server/src/bin/www/index.ts
  auth-server/src/handlers/user-sync-handler.ts
  auth-server/src/middlewares/require-access-token.ts
  auth-server/src/middlewares/require-application.ts
  auth-server/src/routers/user-router.ts
  hr-resource/graphql/schema.graphql
  hr-resource/package-lock.json
  hr-resource/package.json
  hr-resource/prisma/migrations/20240301235321_kaya_52/migration.sql
  hr-resource/prisma/schema.prisma
  hr-resource/src/app.ts
  hr-resource/src/lib/apollo.ts
  hr-resource/src/lib/fetch-requests.ts
  hr-resource/src/lib/gql-codegen/graphql.ts
  hr-resource/src/lib/logger.ts
  hr-resource/src/lib/mutation-resolvers.ts
  hr-resource/src/lib/query-resolvers.ts
  hr-resource/src/lib/resolvers.ts
Labels: enhancement

#31 feature/KAYA-65-Build-list-employees-resolver
  hr-panel/src/lib/gql-codegen/graphql.ts
  hr-resource/graphql/schema.graphql
  hr-resource/src/lib/apollo.ts
  hr-resource/src/lib/gql-codegen/graphql.ts
  hr-resource/src/lib/query-resolvers.ts
Labels: enhancement

#32 feature/KAYA-63-Create-manage-org-details-page
  hr-panel/src/App.tsx
  hr-panel/src/DashboardLayout.tsx
  hr-panel/src/OrganizationSettingsPage.tsx
  hr-panel/src/SettingsPage.tsx
  hr-panel/src/lib/gql-codegen/gql.ts
  hr-panel/src/lib/gql-codegen/graphql.ts
  hr-panel/src/lib/gql-queries.ts
  hr-resource/.env.template
  hr-resource/graphql/schema.graphql
  hr-resource/prisma/migrations/20240304175334_kaya_63/migration.sql
  hr-resource/prisma/schema.prisma
  hr-resource/prisma/seed.js
  hr-resource/src/config/environment.ts
  hr-resource/src/lib/apollo.ts
  hr-resource/src/lib/fetch-requests.ts
  hr-resource/src/lib/gql-codegen/graphql.ts
  hr-resource/src/lib/mutation-resolvers.ts
  hr-resource/src/lib/query-resolvers.ts
Labels: enhancement

#33 feature/KAYA-62-Create-list-employees-page
  auth-server/src/handlers/user-sync-handler.ts
  hr-panel/package-lock.json
  hr-panel/package.json
  hr-panel/src/App.tsx
  hr-panel/src/DashboardLayout.tsx
  hr-panel/src/EmployeeAdd.tsx
  hr-panel/src/EmployeeList.tsx
  hr-panel/src/Home.tsx
  hr-panel/src/OrganizationSettingsPage.tsx
  hr-panel/src/SettingsPage.tsx
  hr-panel/src/ViewEmployee.tsx
  hr-panel/src/components/Banner.tsx
  hr-panel/src/components/ListEmployee.tsx
  hr-panel/src/components/SearchIconWrapper.ts
  hr-panel/src/components/SearchWidget.ts
  hr-panel/src/components/SearchWidgetInputBase.ts
  hr-panel/src/components/SyncInProgressIcon.tsx
  hr-panel/src/lib/gql-codegen/gql.ts
  hr-panel/src/lib/gql-codegen/graphql.ts
  hr-panel/src/lib/gql-queries.ts
  hr-panel/src/lib/material-theme.ts
  hr-resource/.env.template
  hr-resource/graphql/schema.graphql
  hr-resource/src/config/environment.ts
  hr-resource/src/lib/apollo.ts
  hr-resource/src/lib/fetch-requests.ts
  hr-resource/src/lib/gql-codegen/graphql.ts
  hr-resource/src/lib/mutation-resolvers.ts
  hr-resource/src/lib/query-resolvers.ts
Labels: enhancement

#34 bugfix/KAYA-67-Home-list-component-height-and-auth-navigation-bug
  auth-server/src/app.ts
  auth-server/src/bin/www/index.ts
  auth-server/src/handlers/error-handler.ts
  auth-server/src/handlers/user-sync-handler.ts
  auth-server/src/middlewares/require-access-token.ts
  auth-server/src/middlewares/require-application.ts
  auth-server/src/middlewares/require-params.ts
  auth-server/src/middlewares/require-user.ts
  auth-server/src/routers/application-router.ts
  auth-server/src/routers/auth-router.ts
  auth-server/src/routers/user-router.ts
  hr-panel/src/App.tsx
  hr-panel/src/DashboardLayout.tsx
  hr-panel/src/EmployeeAdd.tsx
  hr-panel/src/EmployeeList.tsx
  hr-panel/src/Home.tsx
  hr-panel/src/Layout.tsx
  hr-panel/src/Login.tsx
  hr-panel/src/OrganizationSettingsPage.tsx
  hr-panel/src/SettingsPage.tsx
  hr-panel/src/ViewEmployee.tsx
  hr-panel/src/components/Banner.tsx
  hr-panel/src/components/InputPassword.tsx
  hr-panel/src/components/ListEmployee.tsx
  hr-panel/src/components/PopoverProfile.tsx
  hr-panel/src/components/SelectRole.tsx
  hr-panel/src/components/SyncInProgressIcon.tsx
  hr-panel/src/index.tsx
  hr-panel/src/lib/redux-hooks.ts
  hr-panel/src/lib/redux-store.ts
  hr-panel/src/lib/whoami-provider.ts
  hr-resource/src/app.ts
  hr-resource/src/bin/www/index.ts
  hr-resource/src/lib/apollo.ts
  hr-resource/src/lib/fetch-requests.ts
  hr-resource/src/lib/mutation-resolvers.ts
  hr-resource/src/middlewares/error-handler.ts
  kaya-hr.code-workspace
Labels: bug, enhancement

#36 bugfix/KAYA-42-Auth-logger-logs-undefined-system-exceptions
  auth-server/src/bin/www/index.ts
Labels: bug

#37 feature/KAYA-68-Update-list-users-query-to-process-search-queries
  README.md
  hr-panel/src/lib/gql-codegen/gql.ts
  hr-panel/src/lib/gql-codegen/graphql.ts
  hr-panel/src/lib/gql-queries.ts
  hr-resource/graphql/schema.graphql
  hr-resource/src/lib/gql-codegen/graphql.ts
  hr-resource/src/lib/mutation-resolvers.ts
  hr-resource/src/lib/query-resolvers.ts
Labels: enhancement

#38 feature/KAYA-69-Implement-search-query-with-search-bar-widget
  hr-panel/src/App.tsx
  hr-panel/src/DashboardLayout.tsx
  hr-panel/src/EmployeeEditor.tsx
  hr-panel/src/EmployeeList.tsx
  hr-panel/src/ViewEmployee.tsx
  hr-panel/src/lib/gql-codegen/gql.ts
  hr-panel/src/lib/gql-codegen/graphql.ts
  hr-panel/src/lib/gql-queries.ts
  hr-resource/graphql/schema.graphql
  hr-resource/src/lib/apollo.ts
  hr-resource/src/lib/gql-codegen/graphql.ts
  hr-resource/src/lib/mutation-resolvers.ts
Labels: enhancement

#40 feature/KAYA-10-Setup-React-project
  README.md
  admin-panel/.env.template
  admin-panel/.gitignore
  admin-panel/.vscode/settings.json
  admin-panel/README.md
  admin-panel/codegen.ts
  admin-panel/package-lock.json
  admin-panel/package.json
  admin-panel/public/favicon.ico
  admin-panel/public/index.html
  admin-panel/public/logo-icon-rounded@192w.png
  admin-panel/public/logo-icon-rounded@512w.png
  admin-panel/public/manifest.json
  admin-panel/public/robots.txt
  admin-panel/src/App.test.tsx
  admin-panel/src/App.tsx
  admin-panel/src/assets/logo-full.svg
  admin-panel/src/assets/logo-icon.svg
  admin-panel/src/components/InputPassword.tsx
  admin-panel/src/components/PopoverProfile.tsx
  admin-panel/src/components/ToolbarSpacer.ts
  admin-panel/src/index.tsx
  admin-panel/src/lib/apollo.ts
  admin-panel/src/lib/fetch-requests.ts
  admin-panel/src/lib/gql-codegen/fragment-masking.ts
  admin-panel/src/lib/gql-codegen/gql.ts
  admin-panel/src/lib/gql-codegen/graphql.ts
  admin-panel/src/lib/gql-codegen/index.ts
  admin-panel/src/lib/gql-queries.ts
  admin-panel/src/lib/material-theme.ts
  admin-panel/src/lib/redux-hooks.ts
  admin-panel/src/lib/redux-slice-authentication.ts
  admin-panel/src/lib/redux-slice-ui-preferences.ts
  admin-panel/src/lib/redux-store.ts
  admin-panel/src/lib/whoami-provider.ts
  admin-panel/src/pages/HomePage.tsx
  admin-panel/src/pages/LoginPage.tsx
  admin-panel/src/pages/SettingsPage.tsx
  admin-panel/src/react-app-env.d.ts
  admin-panel/src/reportWebVitals.ts
  admin-panel/src/setupTests.ts
  admin-panel/src/shared/DashboardLayout.tsx
  admin-panel/src/shared/RootLayout.tsx
  admin-panel/tsconfig.json
  kaya-hr.code-workspace
Labels: enhancement, good first issue

#41 feature/KAYA-9-Setup-React-Project
  employee-client-web/.env.template
  employee-client-web/.gitignore
  employee-client-web/.vscode/settings.json
  employee-client-web/README.md
  employee-client-web/codegen.ts
  employee-client-web/package-lock.json
  employee-client-web/package.json
  employee-client-web/public/favicon.ico
  employee-client-web/public/index.html
  employee-client-web/public/logo-icon-rounded@192w.png
  employee-client-web/public/logo-icon-rounded@512w.png
  employee-client-web/public/manifest.json
  employee-client-web/public/robots.txt
  employee-client-web/src/App.test.tsx
  employee-client-web/src/App.tsx
  employee-client-web/src/assets/logo-full.svg
  employee-client-web/src/assets/logo-icon.svg
  employee-client-web/src/components/InputPassword.tsx
  employee-client-web/src/components/PopoverProfile.tsx
  employee-client-web/src/components/ToolbarSpacer.ts
  employee-client-web/src/index.tsx
  employee-client-web/src/lib/apollo.ts
  employee-client-web/src/lib/fetch-requests.ts
  employee-client-web/src/lib/gql-codegen/fragment-masking.ts
  employee-client-web/src/lib/gql-codegen/gql.ts
  employee-client-web/src/lib/gql-codegen/graphql.ts
  employee-client-web/src/lib/gql-codegen/index.ts
  employee-client-web/src/lib/gql-queries.ts
  employee-client-web/src/lib/material-theme.ts
  employee-client-web/src/lib/redux-hooks.ts
  employee-client-web/src/lib/redux-slice-authentication.ts
  employee-client-web/src/lib/redux-slice-ui-preferences.ts
  employee-client-web/src/lib/redux-store.ts
  employee-client-web/src/lib/whoami-provider.ts
  employee-client-web/src/pages/HomePage.tsx
  employee-client-web/src/pages/LoginPage.tsx
  employee-client-web/src/pages/SettingsPage.tsx
  employee-client-web/src/react-app-env.d.ts
  employee-client-web/src/reportWebVitals.ts
  employee-client-web/src/setupTests.ts
  employee-client-web/src/shared/DashboardLayout.tsx
  employee-client-web/src/shared/RootLayout.tsx
  employee-client-web/tsconfig.json
  kaya-hr.code-workspace
Labels: enhancement

#43 feature/KAYA-74-Employee-client-view-schedules
  employee-client-web/src/App.tsx
  employee-client-web/src/components/BorderLinearProgress.tsx
  employee-client-web/src/components/ScheduleAssignmentList.tsx
  employee-client-web/src/components/ScheduleAssignmentListItem.tsx
  employee-client-web/src/lib/gql-codegen/gql.ts
  employee-client-web/src/lib/gql-codegen/graphql.ts
  employee-client-web/src/lib/gql-queries.ts
  employee-client-web/src/pages/HomePage.tsx
  hr-panel/src/lib/gql-codegen/gql.ts
  hr-panel/src/lib/gql-codegen/graphql.ts
  hr-panel/src/lib/gql-queries.ts
  hr-resource/graphql/schema.graphql
  hr-resource/src/lib/apollo.ts
  hr-resource/src/lib/gql-codegen/graphql.ts
  hr-resource/src/lib/query-resolvers.ts
Labels: enhancement

#44 feature/KAYA-75-Manual-clock-in-out-functionality
  employee-client-web/src/App.tsx
  employee-client-web/src/components/PunchFab.tsx
  employee-client-web/src/components/Timer.tsx
  employee-client-web/src/lib/dayjs.ts
  employee-client-web/src/lib/gql-codegen/gql.ts
  employee-client-web/src/lib/gql-codegen/graphql.ts
  employee-client-web/src/lib/gql-queries.ts
  employee-client-web/src/pages/HomePage.tsx
  employee-client-web/src/pages/PunchPage.tsx
  hr-panel/src/lib/gql-codegen/graphql.ts
  hr-resource/graphql/schema.graphql
  hr-resource/package-lock.json
  hr-resource/package.json
  hr-resource/prisma/migrations/20240316144813_kaya_75/migration.sql
  hr-resource/prisma/schema.prisma
  hr-resource/src/lib/apollo.ts
  hr-resource/src/lib/gql-codegen/graphql.ts
  hr-resource/src/lib/mutation-resolvers.ts
  hr-resource/src/lib/query-resolvers.ts
Labels: enhancement

#48 feature/KAYA-78-Create-timesheet-queries-and-resolvers
  employee-client-web/src/components/PunchHistoryItem.tsx
  employee-client-web/src/components/PunchTiming.tsx
  employee-client-web/src/lib/gql-codegen/gql.ts
  employee-client-web/src/lib/gql-codegen/graphql.ts
  employee-client-web/src/pages/PunchPage.tsx
  hr-panel/codegen.ts
  hr-panel/package-lock.json
  hr-panel/package.json
  hr-panel/src/App.tsx
  hr-panel/src/components/DashboardMenu.tsx
  hr-panel/src/components/UserAvatar.tsx
  hr-panel/src/lib/gql-codegen/gql.ts
  hr-panel/src/lib/gql-codegen/graphql.ts
  hr-panel/src/pages/EmployeeEditorPage.tsx
  hr-panel/src/pages/EmployeeList.tsx
  hr-panel/src/pages/PayrollsPage.tsx
  hr-panel/src/pages/ScheduleEditorPage.tsx
  hr-panel/src/pages/ViewEmployee.tsx
  hr-panel/src/shared/DashboardLayout.tsx
  hr-panel/src/shared/PickUserDialog.tsx
  hr-resource/graphql/schema.graphql
  hr-resource/package-lock.json
  hr-resource/package.json
  hr-resource/prisma/migrations/20240325155349_kaya_78/migration.sql
  hr-resource/prisma/migrations/20240325184321_kaya_78/migration.sql
  hr-resource/prisma/schema.prisma
  hr-resource/src/lib/apollo.ts
  hr-resource/src/lib/generate-payslip-document.ts
  hr-resource/src/lib/gql-codegen/graphql.ts
  hr-resource/src/lib/mutation-resolvers.ts
  hr-resource/src/lib/query-resolvers.ts
Labels: enhancement
