Repository eshwinrio/kaya-hr, pull requests merged in 2024-02, with the labels that each got.

#5 feature/KAYA-25-Build-user-registration-endpoint
  auth-server/package-lock.json
  auth-server/package.json
  auth-server/src/app.ts
  auth-server/src/config/environment.ts
  auth-server/src/handlers/error-handler.ts
  auth-server/src/middlewares/require-body.ts
  auth-server/src/middlewares/require-headers.ts
  auth-server/src/routers/user-router.ts
  auth-server/src/tests/environment.test.ts
Labels: enhancement

#6 feature/KAYA-38-Build-a-temporary-email-password-auth-endpoint
  auth-server/.env.template
  auth-server/package-lock.json
  auth-server/package.json
  auth-server/src/app.ts
  auth-server/src/config/environment.ts
  auth-server/src/routers/auth-router.ts
  auth-server/src/tests/environment.test.ts
Labels: enhancement

#7 feature/KAYA-26-Build-token-verification-endpoint
  auth-server/src/lib/token.ts
  auth-server/src/middlewares/require-access-token.ts
  auth-server/src/routers/auth-router.ts
Labels: enhancement

#9 feature/KAYA-14-Configure-GraphQL
  hr-resource/.env.template
  hr-resource/graphql/schema.graphql
  hr-resource/package-lock.json
  hr-resource/package.json
  hr-resource/src/app.ts
  hr-resource/src/bin/www/index.ts
  hr-resource/src/lib/apollo.ts
  hr-resource/tsconfig.json
Labels: enhancement

#11 feature/KAYA-43-Enable-CORS-for-auth
  auth-server/.env.template
  auth-server/package-lock.json
  auth-server/package.json
  auth-server/src/app.ts
  auth-server/src/config/environment.ts
  auth-server/src/middlewares/require-access-token.ts
  auth-server/src/routers/auth-router.ts
  auth-server/src/tests/environment.test.ts
Labels: enhancement

#10 feature/KAYA-33-Build-employee-management-dashboard
  hr-panel/package-lock.json
  hr-panel/package.json
  hr-panel/src/App.tsx
  hr-panel/src/DashboardLayout.tsx
  hr-panel/src/Home.tsx
  hr-panel/src/Layout.tsx
  hr-panel/src/Login.tsx
  hr-panel/src/components/ToolbarSpacer.ts
  hr-panel/src/index.tsx
  hr-panel/src/lib/fetch-requests.ts
  hr-panel/src/lib/material-theme.ts
  hr-panel/src/lib/redux-hooks.ts
  hr-panel/src/lib/redux-slice-authentication.ts
  hr-panel/src/lib/redux-slice-ui-preferences.ts
  hr-panel/src/lib/redux-store.ts
Labels: enhancement

#12 bugfix/KAYA-44-JWT-Expiration-throws-InternalServerError
  auth-server/src/middlewares/require-access-token.ts
Labels: bug

#13 feature/KAYA-45-Design-a-mock-interface-for-index-page
  hr-panel/src/DashboardLayout.tsx
  hr-panel/src/Home.tsx
  hr-panel/src/components/DashCard.ts
  hr-panel/src/lib/material-theme.ts
Labels: enhancement

#15 feature/KAYA-59-Update-enforcer-middlewares-with-new-type-converter
  auth-server/src/middlewares/require-body.ts
  auth-server/src/routers/auth-router.ts
  auth-server/src/routers/user-router.ts
  auth-server/tsconfig.json
Labels: enhancement

#17 feature/KAYA-24-Build-token-invalidation-endpoint
  auth-server/src/routers/auth-router.ts
Labels: enhancement

#18 feature/KAYA-46-Application-registration-endpoint
  auth-server/prisma/schema.prisma
  auth-server/src/app.ts
  auth-server/src/middlewares/require-access-token.ts
  auth-server/src/middlewares/require-params.ts
  auth-server/src/routers/application-router.ts
Labels: enhancement

#19 Added all workspace configurations
  auth-server/.vscode/settings.json
  hr-panel/.vscode/settings.json
  hr-resource/.vscode/settings.json
  kaya-hr.code-workspace
Labels: documentation, enhancement

#20 feature/KAYA-53-Compose-schema-for-application-role-mapping
  auth-server/prisma/migrations/20240218184319_application_role_connector/migration.sql
  auth-server/prisma/schema.prisma
  auth-server/src/lib/token.ts
  auth-server/src/middlewares/require-application.ts
  auth-server/src/routers/auth-router.ts
Labels: enhancement

#22 feature/KAYA-29-Compose-a-middleware-for-application-role-checking
  auth-server/src/middlewares/check-application-roles.ts
  auth-server/src/middlewares/require-access-token.ts
  auth-server/src/middlewares/require-application.ts
  auth-server/src/routers/auth-router.ts
Labels: enhancement

#25 feature/KAYA-58-Build-form-for-employee-registration
  hr-panel/package-lock.json
  hr-panel/package.json
  hr-panel/src/App.tsx
  hr-panel/src/DashboardLayout.tsx
  hr-panel/src/EmployeeAdd.tsx
Labels: enhancement

#27 feature/KAYA-50-Compose-employee-registration-mutation
  auth-server/package.json
  hr-panel/src/App.tsx
  hr-panel/src/EmployeeAdd.tsx
  hr-panel/src/components/InputPassword.tsx
  hr-panel/src/components/SelectRole.tsx
  hr-panel/src/lib/gql-codegen/gql.ts
  hr-panel/src/lib/gql-codegen/graphql.ts
  hr-panel/src/lib/gql-queries.ts
  hr-resource/graphql/schema.graphql
  hr-resource/package.json
  hr-resource/prisma/migrations/20240208191349_init/migration.sql
  hr-resource/prisma/migrations/20240229204254_kaya_50/migration.sql
  hr-resource/prisma/schema.prisma
  hr-resource/src/lib/apollo.ts
  hr-resource/src/lib/gql-codegen/graphql.ts
  hr-resource/src/lib/resolvers.ts
Labels: enhancement
